# azure-pipelines.yml
# Azure Pipeline for terraform-aks

variables:
- group: terraform-aks

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
- master

steps:
- task: AzureCLI@1
  inputs:
    azureSubscription: '$(devops_subscription)'
    scriptLocation: 'inlineScript'
    inlineScript: 'az extension add -n azure-firewall'

- task: DownloadSecureFile@1
  inputs:
   secureFile: 'dev.tfvars'

- task: AzureCLI@1
  inputs:
    azureSubscription: '$(devops_subscription)'
    scriptLocation: 'scriptPath'
    scriptPath: 'tf_validate_all.sh'
    arguments: '-e dev -p 4711 -v $(Agent.TempDirectory)/dev.tfvars -f'
    addSpnToEnvironment: true
    failOnStandardError: true
