# Azure Pipeline using bash.
# azure-pipelines.yml

pool:
  vmImage: 'Ubuntu 16.04'
resources:
  containers:
  - container: terraform-latest
    image: hashicorp/terraform:latest


trigger:
- master

jobs:
- job: terraform-validate
  container: terraform-latest
  failOnStderr: true
  steps:
  - script: 'terraform init && terraform validate'