# azure-pipelines.yml
# Azure Pipeline for terraform-aks

variables:
- group: terraform-aks

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
- master

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: 'dev.tfvars'

- task: AzureCLI@1
  inputs:
    azureSubscription: 'aks-terraform'
    scriptLocation: 'inlineScript'
    inlineScript: 'az extension add -n azure-firewall'

- task: AzureCLI@1
  inputs:
    azureSubscription: 'aks-terraform'
    scriptLocation: 'inlineScript'
    inlineScript: 'env'

- task: AzureCLI@1
  inputs:
    azureSubscription: 'aks-terraform'
    scriptLocation: 'scriptPath'
    scriptPath: 'tf_apply_all.1.sh'
    arguments: '-e dev -p 4711 -i $(Agent.TempDirectory)/dev.tfvars -v -f'
