# azure-pipelines.yml
# Azure Pipeline for terraform-aks

variables:
- group: terraform-aks

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
- master

steps:
- task: DownloadSecureFile@1
  name: "downloading_dev_tfvars"
  inputs:
    secureFile: 'dev.tfvars'

- task: DownloadSecureFile@1
  name: "downloading_id_rsa_pub"
  inputs:
    secureFile: 'id_rsa.pub'


- task: AzureCLI@1
  name: "azurecli_prep"
  inputs:
    azureSubscription: 'aks-terraform'
    scriptLocation: 'inlineScript'
    inlineScript: 'az extension add -n azure-firewall && mkdir ~/.ssh/ && cp $(Agent.TempDirectory)/id_rsa.pub ~/.ssh/'

- task: AzureCLI@1
  name: "terraform_DRYRUN"
  env:
    __TF_AAD_CLIENT_APP_ID: $(__TF_aad_client_app_id)
    __TF_AAD_TENANT_ID: $(__TF_aad_tenant_id)
    __TF_STORAGE_ACCOUNT_PRIMARY_ACCESS_KEY: $(__TF_storage_account_primary_access_key)
  inputs:
    azureSubscription: 'aks-terraform'
    scriptLocation: 'scriptPath'
    scriptPath: 'run_tf.sh'
    arguments: '-e dev -i $(Agent.TempDirectory)/dev.tfvars -v -f'
    addSpnToEnvironment: true
