# Azure Pipeline using bash.
# azure-pipelines.yml

trigger:
- master

resources:
  containers:
  - container: terraformlatest
    image: ubuntu:latest


jobs:

- job: terraformvalidate
  displayName: Terraform Validate
  pool:
    vmImage: 'Ubuntu 16.04'
  container: terraformlatest
  steps:
  - script: |
      terraform version
