# azure-pipelines.yml
# Azure Pipeline for terraform-aks

variables:
- group: terraform-aks

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
- master

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'dev.tfvars'

- task: AzureCLI@1
  inputs:
    azureSubscription: 'aks-terraform'
    scriptLocation: 'inlineScript'
    inlineScript: 'az extension add -n azure-firewall'

