# Azure Pipeline using bash.
# azure-pipelines.yml

pool:
  vmImage: 'Ubuntu 16.04'

trigger:
- master

steps:
- task: AzureCLI@1
  inputs:
    azureSubscription: 'Darius-Azure Internal Consumption(a4ec924c-502f-4820-9549-1bbcce0dbb52)'
    scriptLocation: 'inlineScript'
    inlineScript: 'az extension add -n azure-firewall'

- task: AzureCLI@1
  inputs:
    azureSubscription: 'Darius-Azure Internal Consumption(a4ec924c-502f-4820-9549-1bbcce0dbb52)'
    scriptLocation: 'scriptPath'
    scriptPath: 'tf_validate_all.sh'
    arguments: '-e dev -p 4711 -v darius.tfvars -f'
    addSpnToEnvironment: true
    failOnStandardError: true