apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eshopweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshopweb
  template:
    metadata:
      labels:
        app: eshopweb
    spec:
      containers:
      - name: eshopweb
        image: 4711demo.azurecr.io/eshopweb:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: eshop-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: eshopweb

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
   kubernetes.io/ingress.class: "nginx"
   certmanager.k8s.io/issuer: "letsencrypt-staging"
   certmanager.k8s.io/acme-challenge-type: http01
  name: eshopweb
  namespace: ops
spec:
  tls:
  - hosts:
          - app1.4711.cloud
    secretName: app1-4711-cloud
  rules:
  - host: app1.4711.cloud
    http:
      paths:
      - backend:
          serviceName: eshop-svc
          servicePort: 80
        path: /